### ISSUE TITLE
Support hash fragment in URL

### ISSUE THREAD

**Issue by exoego** [codefirst/AsakusaSatellite#210]
AS seems to remove "hash fragement in URL" in post, when it expand the URL into a fancy clip.

There are 2 popular use cases for using hash fragment.
1. Anchor to jump to specifict location on a web page (e.#section-1).
2. To indicate state of resource on a dynamic web page. (#!foo, #/bar)

1 is obviously standard and useful, which should be supported, IMO.
2 is recently considered bad practice, since pushState API came on web standard. Though that trends, using hash-fragment for use case 2 is so far from vanished.

**Comment by mallowlabs** [comment]
It is a feature of [QuoteIt](https://github.com/codefirst/QuoteIt).
And QuoteIt does NOT remove hash fragments and hashbangs.
For example, try below URLs and check quoted urls.
 * https://github.com/#aws
 * https://twitter.com/#!/mzp
 
But there are 2 problems:
1. Redirection sometimes removes hash fragments.
2. Hashbang is browser feature which needs javascript, so it is too difficult to support on a web application.

If you have good idea to resolve these problems, please send us pull-request!

**Comment by exoego** [comment]
Yes, AS keeps hash fragment if https used, but removes if http used.

> "too dificult to support on a web application"
Do you mean that it is hard to make QuoteIt capable to quote the section specified by hash fragment ?
If my understanding is correct, I agree that.
But, what I wanna point in this issue is that AS/QuoteIt keeps hash fragment simply in the clips that it generates.

**Comment by mzp** [comment]
It works at mine. Send a example URL or pull requests.

**Comment by exoego** [comment]
Oh, sorry. I forgot to show example for repro.

Try these.
http://github.com/#aws
http://www.google.co.jp/trends/explore#q=java%2C%20ruby&cmpt=q&tz=

Hash fragment were removed when I posted those on AS hosted on
http://asakusa-satellite.org/chat/room/4e3600462620a454d9000bf2

**Comment by mallowlabs** [comment]
OK, I understand this problem.
If a site has an OpenGraph tag and the tag is wrong, quoted URL will be wrong.
Your example URLs both have this problem.

I changed this behavior in https://github.com/codefirst/QuoteIt/pull/26 .
Please try again.

**Comment by exoego** [comment]
[![LGTM](http://www.lgtm.in/p/WJALdPvZp)](http://www.lgtm.in/i/WJALdPvZp)
